export const PROD_POST_REQ="PROD_POST_REQ";
export const PROD_POST_SUCC="PROD_POST_SUCC";
export const PROD_POST_FAIL="PROD_POST_FAIL";
export const GET_PRODUCT="GET_PRODUCT"
export const EDIT_PRODUCT="EDIT_PRODUCT"
export const DELETE_PRODUCT="DELETE_PRODUCT"